version: "3"

services:
  postgres:
    container_name: postgres-docker
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres-docker
    volumes:
      - pg-data:/data/postgres
    ports:
      - "5432:5432"

  backend:
    build: .
    command: yarn dev
    ports:
      - "3333:3333"
    volumes:
      - .:/backend
volumes:
  pg-data: